Insert into bridge VALUES (null, null, 'Abkhazia');
Insert into bridge VALUES ('Afghanistan', 'AFG', 'Afghanistan');
Insert into bridge VALUES (null, null, 'Akrotiri and Dhekelia');
Insert into bridge VALUES (null, null, 'Åland');
Insert into bridge VALUES ('Albania', 'AL', 'Albania');
Insert into bridge VALUES ('Algeria', 'DZ', 'Algeria');
Insert into bridge VALUES ('American Samoa', 'AMSA', 'American Samoa');
Insert into bridge VALUES ('Andorra', 'AND', 'Andorra');
Insert into bridge VALUES ('Angola', 'ANG', 'Angola');
Insert into bridge VALUES ('Anguilla', 'AXA', 'Anguilla');
Insert into bridge VALUES ('Antigua and Barbuda', 'AG', 'Antigua and Barbuda');
Insert into bridge VALUES ('Argentina', 'RA', 'Argentina');
Insert into bridge VALUES ('Armenia', 'ARM', 'Armenia');
Insert into bridge VALUES ('Aruba', 'ARU', 'Aruba');
Insert into bridge VALUES ('Australia', 'AUS', 'Australia');
Insert into bridge VALUES ('Austria', 'A', 'Austria');
Insert into bridge VALUES ('Azerbaijan', 'AZ', 'Azerbaijan');
Insert into bridge VALUES ('Bahamas', 'BS', 'Bahamas');
Insert into bridge VALUES ('Bahrain', 'BRN', 'Bahrain');
Insert into bridge VALUES ('Bangladesh', 'BD', 'Bangladesh');
Insert into bridge VALUES ('Barbados', 'BDS', 'Barbados');
Insert into bridge VALUES ('Belarus', 'BY', 'Belarus');
Insert into bridge VALUES ('Belgium', 'B', 'Belgium');
Insert into bridge VALUES ('Belize', 'BZ', 'Belize');
Insert into bridge VALUES ('Benin', 'BEN', 'Benin');
Insert into bridge VALUES ('Bermuda', 'BERM', 'Bermuda');
Insert into bridge VALUES ('Bhutan', 'BHT', 'Bhutan');
Insert into bridge VALUES ('Bolivia', 'BOL', 'Bolivia');
Insert into bridge VALUES ('Bosnia and Herzegovina', 'BIH', 'Bosnia and Herzegovina');
Insert into bridge VALUES ('Botswana', 'RB', 'Botswana');
Insert into bridge VALUES ('Brazil', 'BR', 'Brazil');
Insert into bridge VALUES ('British Virgin Islands', 'BVIR', 'British Virgin Islands');
Insert into bridge VALUES ('Brunei', 'BRU', 'Brunei');
Insert into bridge VALUES ('Bulgaria', 'BG', 'Bulgaria');
Insert into bridge VALUES ('Burkina Faso', 'BF', 'Burkina Faso');
Insert into bridge VALUES ('Burundi', 'BI', 'Burundi');
Insert into bridge VALUES ('Cambodia', 'K', 'Cambodia');
Insert into bridge VALUES ('Cameroon', 'CAM', 'Cameroon');
Insert into bridge VALUES ('Canada', 'CDN', 'Canada');
Insert into bridge VALUES ('Cape Verde', 'CV', 'Cape Verde');
Insert into bridge VALUES ('Cayman Islands', 'CAYM', 'Cayman Islands');
Insert into bridge VALUES ('Central African Republic', 'RCA', 'Central African Rep.');
Insert into bridge VALUES ('Chad', 'TCH', 'Chad');
Insert into bridge VALUES (null, null, 'Channel Islands');
Insert into bridge VALUES ('Chile', 'RCH', 'Chile');
Insert into bridge VALUES ('China', 'TJ', 'China');
Insert into bridge VALUES ('Christmas Island', 'XMAS', 'Christmas Island');
Insert into bridge VALUES ('Cocos Islands', 'COCO', 'Cocos Island');
Insert into bridge VALUES ('Colombia', 'CO', 'Colombia');
Insert into bridge VALUES ('Comoros', 'COM', 'Comoros');
Insert into bridge VALUES ('Cook Islands', 'COOK', 'Cook Islands');
Insert into bridge VALUES ('Costa Rica', 'CR', 'Costa Rica');
Insert into bridge VALUES ('Cote dIvoire', 'CI', 'Cote d''Ivoire');
Insert into bridge VALUES ('Croatia', 'HR', 'Croatia');
Insert into bridge VALUES ('Cuba', 'C', 'Cuba');
Insert into bridge VALUES ('Cyprus', 'CY', 'Cyprus');
Insert into bridge VALUES (null, null, 'Czechoslovakia');
Insert into bridge VALUES ('Czech Republic', 'CZ', 'Czech Rep.');
Insert into bridge VALUES ('Denmark', 'DK', 'Denmark');
Insert into bridge VALUES ('Djibouti', 'DJI', 'Djibouti');
Insert into bridge VALUES ('Dominica', 'WD', 'Dominica');
Insert into bridge VALUES ('Dominican Republic', 'DOM', 'Dominican Rep.');
Insert into bridge VALUES ('Germany', 'D', 'East Germany');
Insert into bridge VALUES ('Ecuador', 'EC', 'Ecuador');
Insert into bridge VALUES ('Egypt', 'ET', 'Egypt');
Insert into bridge VALUES ('El Salvador', 'ES', 'El Salvador');
Insert into bridge VALUES ('Equatorial Guinea', 'GQ', 'Equatorial Guinea');
Insert into bridge VALUES ('Eritrea', 'ER', 'Eritrea');
Insert into bridge VALUES (null, null, 'Eritrea and Ethiopia');
Insert into bridge VALUES ('Estonia', 'EW', 'Estonia');
Insert into bridge VALUES ('Ethiopia', 'ETH', 'Ethiopia');
Insert into bridge VALUES ('Falkland Islands', 'FALK', '');
Insert into bridge VALUES ('Faroe Islands', 'FARX', 'Faeroe Islands');
Insert into bridge VALUES (null, null, 'Falkland Islands (Malvinas)');
Insert into bridge VALUES ('Fiji', 'FJI', 'Fiji');
Insert into bridge VALUES ('Finland', 'SF', 'Finland');
Insert into bridge VALUES ('France', 'F', 'France');
Insert into bridge VALUES ('French Guiana', 'FGU', 'French Guiana');
Insert into bridge VALUES ('French Polynesia', 'FPOL', 'French Polynesia');
Insert into bridge VALUES ('Gabon', 'G', 'Gabon');
Insert into bridge VALUES ('Gambia', 'WAG', 'Gambia');
Insert into bridge VALUES ('Gaza Strip', 'GAZA', '');
Insert into bridge VALUES ('Georgia', 'GE', 'Georgia');
Insert into bridge VALUES ('Germany', 'D', 'Germany');
Insert into bridge VALUES ('Ghana', 'GH', 'Ghana');
Insert into bridge VALUES ('Gibraltar', 'GBZ', 'Gibraltar');
Insert into bridge VALUES ('Greece', 'GR', 'Greece');
Insert into bridge VALUES ('Greenland', 'GROX', 'Greenland');
Insert into bridge VALUES ('Grenada', 'WG', 'Grenada');
Insert into bridge VALUES ('Guadeloupe', 'GUAD', 'Guadeloupe');
Insert into bridge VALUES ('Guam', 'GUAM', 'Guam');
Insert into bridge VALUES ('Guatemala', 'GCA', 'Guatemala');
Insert into bridge VALUES ('Guernsey', 'GBG', 'Guernsey');
Insert into bridge VALUES ('Guinea', 'RG', 'Guinea');
Insert into bridge VALUES ('Guinea-Bissau', 'GNB', 'Guinea-Bissau');
Insert into bridge VALUES ('Guyana', 'GUY', 'Guyana');
Insert into bridge VALUES ('Haiti', 'RH', 'Haiti');
Insert into bridge VALUES ('Holy See', 'V', 'Holy See');
Insert into bridge VALUES ('Honduras', 'HCA', 'Honduras');
Insert into bridge VALUES ('Hungary', 'H', 'Hungary');
Insert into bridge VALUES ('Iceland', 'IS', 'Iceland');
Insert into bridge VALUES ('India', 'IND', 'India');
Insert into bridge VALUES ('Indonesia', 'RI', 'Indonesia');
Insert into bridge VALUES ('Iran', 'IR', 'Iran');
Insert into bridge VALUES ('Iraq', 'IRQ', 'Iraq');
Insert into bridge VALUES ('Ireland', 'IRL', 'Ireland');
Insert into bridge VALUES (null, null, 'Isle of Man');
Insert into bridge VALUES ('Israel', 'IL', 'Israel');
Insert into bridge VALUES ('Italy', 'I', 'Italy');
Insert into bridge VALUES ('Jamaica', 'JA', 'Jamaica');
Insert into bridge VALUES ('Japan', 'J', 'Japan');
Insert into bridge VALUES ('Jersey', 'GBJ', 'Jersey');
Insert into bridge VALUES ('Jordan', 'JOR', 'Jordan');
Insert into bridge VALUES ('Kazakstan', 'KAZ', 'Kazakhstan');
Insert into bridge VALUES ('Kenya', 'EAK', 'Kenya');
Insert into bridge VALUES ('Kiribati', 'KIR', 'Kiribati');
Insert into bridge VALUES ('Kosovo', 'KOS', 'Kosovo');
Insert into bridge VALUES ('Kuwait', 'KWT', 'Kuwait');
Insert into bridge VALUES ('Kyrgyzstan', 'KGZ', 'Kyrgyzstan');
Insert into bridge VALUES ('Laos', 'LAO', 'Laos');
Insert into bridge VALUES ('Latvia', 'LV', 'Latvia');
Insert into bridge VALUES ('Lebanon', 'RL', 'Lebanon');
Insert into bridge VALUES ('Lesotho', 'LS', 'Lesotho');
Insert into bridge VALUES ('Liberia', 'LB', 'Liberia');
Insert into bridge VALUES ('Libya', 'LAR', 'Libya');
Insert into bridge VALUES ('Liechtenstein', 'FL', 'Liechtenstein');
Insert into bridge VALUES ('Lithuania', 'LT', 'Lithuania');
Insert into bridge VALUES ('Luxembourg', 'L', 'Luxembourg');
Insert into bridge VALUES ('Madagascar', 'RM', 'Madagascar');
Insert into bridge VALUES ('Malawi', 'MW', 'Malawi');
Insert into bridge VALUES ('Malaysia', 'MAL', 'Malaysia');
Insert into bridge VALUES ('Maldives', 'MV', 'Maldives');
Insert into bridge VALUES ('Mali', 'RMM', 'Mali');
Insert into bridge VALUES ('Malta', 'M', 'Malta');
Insert into bridge VALUES ('Man', 'GBM', null);
Insert into bridge VALUES ('Marshall Islands', 'MH', 'Marshall Islands');
Insert into bridge VALUES ('Martinique', 'MART', 'Martinique');
Insert into bridge VALUES ('Mauritania', 'RIM', 'Mauritania');
Insert into bridge VALUES ('Mauritius', 'MS', 'Mauritius');
Insert into bridge VALUES ('Mayotte', 'MAYO', 'Mayotte');
Insert into bridge VALUES ('Mexico', 'MEX', 'Mexico');
Insert into bridge VALUES ('Moldova', 'MD', 'Moldova');
Insert into bridge VALUES ('Monaco', 'MC', 'Monaco');
Insert into bridge VALUES ('Mongolia', 'MNG', 'Mongolia');
Insert into bridge VALUES ('Montenegro', 'MNE', 'Montenegro');
Insert into bridge VALUES ('Montserrat', 'MNTS', 'Montserrat');
Insert into bridge VALUES ('Morocco', 'MA', 'Morocco');
Insert into bridge VALUES ('Mozambique', 'MOC', 'Mozambique');
Insert into bridge VALUES ('Myanmar', 'MYA', 'Myanmar');
Insert into bridge VALUES ('Namibia', 'NAM', 'Namibia');
Insert into bridge VALUES ('Nauru', 'NAU', 'Nauru');
Insert into bridge VALUES ('Nepal', 'NEP', 'Nepal');
Insert into bridge VALUES ('Netherlands', 'NL', 'Netherlands');
Insert into bridge VALUES ('Netherlands Antilles', 'NA', 'Netherlands Antilles');
Insert into bridge VALUES ('New Caledonia', 'NCA', 'New Caledonia');
Insert into bridge VALUES ('New Zealand', 'NZ', 'New Zealand');
Insert into bridge VALUES (null, null, 'Ngorno-Karabakh');
Insert into bridge VALUES (null, null, 'Nagorno-Karabakh');
Insert into bridge VALUES ('Nicaragua', 'NIC', 'Nicaragua');
Insert into bridge VALUES ('Niger', 'RN', 'Niger');
Insert into bridge VALUES ('Nigeria', 'WAN', 'Nigeria');
Insert into bridge VALUES ('Niue', 'NIUE', 'Niue');
Insert into bridge VALUES ('Norfolk Island', 'NORF', 'Norfolk Island');
Insert into bridge VALUES (null, null, 'Northern Cyprus');
Insert into bridge VALUES ('Northern Mariana Islands', 'NMIS', 'Northern Mariana Islands');
Insert into bridge VALUES ('North Korea', 'NOK', null);
Insert into bridge VALUES ('Norway', 'N', 'Norway');
Insert into bridge VALUES ('Oman', 'OM', 'Oman');
Insert into bridge VALUES ('Pakistan', 'PK', 'Pakistan');
Insert into bridge VALUES ('Palau', 'PAL', 'Palau');
Insert into bridge VALUES ('Panama', 'PA', 'Panama');
Insert into bridge VALUES ('Papua New Guinea', 'PNG', 'Papua New Guinea');
Insert into bridge VALUES ('Paraguay', 'PY', 'Paraguay');
Insert into bridge VALUES ('Peru', 'PE', 'Peru');
Insert into bridge VALUES ('Philippines', 'RP', 'Philippines');
Insert into bridge VALUES ('Pitcairn Islands', 'PITC', 'Pitcairn');
Insert into bridge VALUES ('Poland', 'PL', 'Poland');
Insert into bridge VALUES ('Portugal', 'P', 'Portugal');
Insert into bridge VALUES ('Puerto Rico', 'PR', 'Puerto Rico');
Insert into bridge VALUES ('Qatar', 'Q', 'Qatar');
Insert into bridge VALUES ('Reunion', 'REUN', 'Reunion');
Insert into bridge VALUES ('Romania', 'RO', 'Romania');
Insert into bridge VALUES ('Russia', 'R', 'Russia');
Insert into bridge VALUES ('Rwanda', 'RWA', 'Rwanda');
Insert into bridge VALUES (null, null, 'Saint Barthélemy');
Insert into bridge VALUES ('Saint Helena', 'HELX', 'Saint Helena');
Insert into bridge VALUES ('Saint Kitts and Nevis', 'KN', 'Saint Kitts and Nevis');
Insert into bridge VALUES ('Saint Lucia', 'WL', 'Saint Lucia');
Insert into bridge VALUES ('Saint Martin', 'SMAR', 'Saint Martin');
Insert into bridge VALUES ('Saint Pierre and Miquelon', 'SPMI', 'Saint-Pierre-et-Miquelon');
Insert into bridge VALUES ('Saint Vincent and the Grenadines', 'WV', 'Saint Vincent and the Grenadines');
Insert into bridge VALUES ('Samoa', 'WS', 'Samoa');
Insert into bridge VALUES ('San Marino', 'RSM', 'San Marino');
Insert into bridge VALUES ('Sao Tome and Principe', 'STP', 'Sao Tome and Principe');
Insert into bridge VALUES ('Saudi Arabia', 'SA', 'Saudi Arabia');
Insert into bridge VALUES ('Senegal', 'SN', 'Senegal');
Insert into bridge VALUES ('Serbia', 'SRB', 'Serbia');
Insert into bridge VALUES (null, null, 'Serbia and Montenegro');
Insert into bridge VALUES (null, null, 'Serbia excluding Kosovo');
Insert into bridge VALUES ('Seychelles', 'SY', 'Seychelles');
Insert into bridge VALUES ('Sierra Leone', 'WAL', 'Sierra Leone');
Insert into bridge VALUES ('Singapore', 'SGP', 'Singapore');
Insert into bridge VALUES ('Slovakia', 'SK', 'Slovak Republic');
Insert into bridge VALUES ('Slovenia', 'SLO', 'Slovenia');
Insert into bridge VALUES ('Solomon Islands', 'SLB', 'Solomon Islands');
Insert into bridge VALUES ('Somalia', 'SP', 'Somalia');
Insert into bridge VALUES (null, null, 'Somaliland');
Insert into bridge VALUES ('South Africa', 'RSA', 'South Africa');
Insert into bridge VALUES ('South Korea', 'ROK', '');
Insert into bridge VALUES (null, null, 'South Ossetia');
Insert into bridge VALUES ('Spain', 'E', 'Spain');
Insert into bridge VALUES ('Sri Lanka', 'CL', 'Sri Lanka');
Insert into bridge VALUES ('Sudan', 'SUD', 'Sudan');
Insert into bridge VALUES ('Suriname', 'SME', 'Suriname');
Insert into bridge VALUES ('Svalbard', 'SVAX', 'Svalbard');
Insert into bridge VALUES ('Swaziland', 'SD', 'Swaziland');
Insert into bridge VALUES ('Sweden', 'S', 'Sweden');
Insert into bridge VALUES ('Switzerland', 'CH', 'Switzerland');
Insert into bridge VALUES ('Syria', 'SYR', 'Syria');
Insert into bridge VALUES ('Taiwan', 'RC', 'Taiwan');
Insert into bridge VALUES ('Tajikistan', 'TAD', 'Tajikistan');
Insert into bridge VALUES ('Tanzania', 'EAT', 'Tanzania');
Insert into bridge VALUES ('Thailand', 'THA', 'Thailand');
Insert into bridge VALUES ('Timor-Leste', 'TL', 'Timor-Leste');
Insert into bridge VALUES ('Togo', 'RT', 'Togo');
Insert into bridge VALUES (null, null, 'Tokelau');
Insert into bridge VALUES ('Tonga', 'TO', 'Tonga');
Insert into bridge VALUES (null, null, 'Transnistria');
Insert into bridge VALUES ('Trinidad and Tobago', 'TT', 'Trinidad and Tobago');
Insert into bridge VALUES ('Tunisia', 'TN', 'Tunisia');
Insert into bridge VALUES ('Turkey', 'TR', 'Turkey');
Insert into bridge VALUES ('Turkmenistan', 'TM', 'Turkmenistan');
Insert into bridge VALUES ('Turks and Caicos Islands', 'TUCA', 'Turks and Caicos Islands');
Insert into bridge VALUES ('Tuvalu', 'TUV', 'Tuvalu');
Insert into bridge VALUES ('Uganda', 'EAU', 'Uganda');
Insert into bridge VALUES ('Ukraine', 'UA', 'Ukraine');
Insert into bridge VALUES ('United Arab Emirates', 'UAE', 'United Arab Emirates');
Insert into bridge VALUES ('United Kingdom', 'GB', 'United Kingdom');
Insert into bridge VALUES ('United States', 'USA', 'United States');
Insert into bridge VALUES ('Uruguay', 'ROU', 'Uruguay');
Insert into bridge VALUES (null, null, 'USSR');
Insert into bridge VALUES ('Uzbekistan', 'UZB', 'Uzbekistan');
Insert into bridge VALUES ('Vanuatu', 'VU', 'Vanuatu');
Insert into bridge VALUES ('Venezuela', 'YV', 'Venezuela');
Insert into bridge VALUES ('Vietnam', 'VN', 'Vietnam');
Insert into bridge VALUES ('Virgin Islands', 'VIRG', 'Virgin Islands (U.S.)');
Insert into bridge VALUES ('Wallis and Futuna', 'WAFU', 'Wallis et Futuna');
Insert into bridge VALUES ('West Bank', 'WEST', 'West Bank and Gaza');
Insert into bridge VALUES ('Western Sahara', 'WSA', 'Western Sahara');
Insert into bridge VALUES ('Germany', 'D', 'West Germany');
Insert into bridge VALUES (null, null, 'Yemen Arab Republic (Former)');
Insert into bridge VALUES (null, null, 'Yemen Democratic (Former)');
Insert into bridge VALUES ('Zaire', 'ZRE', '');
Insert into bridge VALUES (null, null, 'Yugoslavia');
Insert into bridge VALUES ('Zambia', 'Z', 'Zambia');
Insert into bridge VALUES ('Zimbabwe', 'ZW', 'Zimbabwe');
Insert into bridge VALUES('Congo', 'RCB', 'Congo, Dem. Rep.');
Insert into bridge VALUES (null, null, 'Congo, Rep.');
Insert into bridge VALUES ('Hong Kong', 'HONX', 'Hong Kong, China');
Insert into bridge VALUES (null, null, 'Korea, Dem. Rep.');
Insert into bridge VALUES (null, null, 'Korea, Rep.');
Insert into bridge VALUES (null, null, 'Korea, Dem.');
Insert into bridge VALUES ('Macau', 'MACX', 'Macao, China');
Insert into bridge VALUES ('Micronesia', 'FSM', 'Micronesia, Fed. Sts.');
Insert into bridge VALUES ('Macedonia', 'MK', 'Macedonia, FYR');
Insert into bridge VALUES ('Yemen', 'YE', 'Yemen, Rep.');
